-- ADDRESS TABLE

-- DDL 

CREATE TABLE ADDRESS
(
	ADDRESS_ID VARCHAR(20)
	, STREET VARCHAR(259)
	, CITY VARCHAR(100)
	, STATE VARCHAR(100)
	, COUNTRY VARCHAR(100)
	, CONSTRAINT PK_ADDRESS PRIMARY KEY(ADDRESS_ID)
);

INSERT INTO ADDRESS VALUES
('ADR1001', '44940 Bluestem Circle', 'Baton Rouge', 'Louisiana', 'United States');

SELECT * FROM ADDRESS;

-- SCHOOL TABLE

CREATE TABLE SCHOOL
(
	SCHOOL_ID VARCHAR(20)
	, SCHOOL_NAME VARCHAR(100)
	, EDUCATION_BOARD VARCHAR(80)
	, ADDRESS_ID VARCHAR(20)
	, CONSTRAINT PK_SCHLOOL_ID PRIMARY KEY(SCHOOL_ID)
	, CONSTRAINT FK_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);

INSERT INTO SCHOOL VALUES
('SCHL1001', 'NOBLE SCHOOL', 'CBSE', 'ADR1001');

SELECT * FROM SCHOOL;

-- STAFF TABLE

CREATE TABLE STAFF
(
	STAFF_ID VARCHAR(20)
	, STAFF_TYPE VARCHAR(30)
	, SCHOOL_ID VARCHAR(20)
	, FIRST_NAME VARCHAR(100) NOT NULL
	, LAST_NAME VARCHAR(100) NOT NULL
	, AGE INT
	, DOB DATE
	, GENDER VARCHAR CHECK (GENDER IN ('M', 'F'))
	, JOIN_DATE DATE
	, ADDRESS_ID VARCHAR(20)
	, CONSTRAINT PK_STF PRIMARY KEY(STAFF_ID)
	, CONSTRAINT FK_STAFF_SCHL FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL(SCHOOL_ID)
	, CONSTRAINT FK_STAFF_ADDR FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);

SELECT * FROM STAFF;


INSERT INTO STAFF (STAFF_ID, STAFF_TYPE, SCHOOL_ID, FIRST_NAME, LAST_NAME, AGE, DOB, GENDER, JOIN_DATE, ADDRESS_ID) VALUES
('STF2004', 'Non-Teaching', 'SCHL1001', 'Shamala', 'Devi', '56', TO_DATE('03/09/1964', 'DD/MM/YYYY'), 'F', TO_DATE('05/06/2015', 'DD/MM/YYYY'), 'ADR1001');


INSERT INTO STAFF (STAFF_ID, STAFF_TYPE, SCHOOL_ID, FIRST_NAME, LAST_NAME, AGE, DOB, GENDER, JOIN_DATE, ADDRESS_ID) VALUES
('STF2004', 'Non-Teaching', 'SCHL1001', 'Shamala', NULL, '56', TO_DATE('03/09/1964', 'DD/MM/YYYY'), 'F', TO_DATE('05/06/2015', 'DD/MM/YYYY'), 'ADR1001');


INSERT INTO STAFF (STAFF_ID, STAFF_TYPE, SCHOOL_ID, FIRST_NAME, LAST_NAME, AGE, DOB, GENDER, JOIN_DATE, ADDRESS_ID) VALUES
('STF2004', 'Non-Teaching', 'SCHL1001', 'Shamala', 'Devi', '56', TO_DATE('03/09/1964', 'DD/MM/YYYY'), 'F', TO_DATE('05/06/2015', 'DD/MM/YYYY'), 'ADR1001');



INSERT INTO STAFF (STAFF_ID, STAFF_TYPE, SCHOOL_ID, FIRST_NAME, LAST_NAME, AGE, DOB, GENDER, JOIN_DATE, ADDRESS_ID) VALUES
('STF2005', 'Non-Teaching', 'SCHL1001', 'Shamala', 'Devi', '56', TO_DATE('03/09/1964', 'DD/MM/YYYY'), 'F', TO_DATE('05/06/2015', 'DD/MM/YYYY'), 'ADR101');

SELECT * FROM STAFF;

-- STUDENT TABLE

CREATE TABLE STUDENT
(
	STUDENT_ID INT
	, FIRST_NAME VARCHAR(20)
	, LAST_NAME VARCHAR(20)
	, AGE INT
	, EMAIL_ID VARCHAR(50)
	, CONSTRAINT STD_ID PRIMARY KEY(STUDENT_ID)
);

SELECT * FROM STUDENT;

INSERT INTO STUDENT VALUES
(1, 'TOUHIDUZZAMAN', 'TUHIN', 27, 'tuhin@xyz.com');

SELECT * FROM STUDENT;
ALTER TABLE STUDENT DROP COLUMN LAST_NAME;
SELECT * FROM STUDENT;
ALTER TABLE STUDENT ALTER COLUMN AGE TYPE VARCHAR(10);
SELECT * FROM STUDENT;
ALTER TABLE STUDENT RENAME TO STUDENTS;
SELECT * FROM STUDENTS;
ALTER TABLE STUDENTS RENAME COLUMN FIRST_NAME TO FULL_NAME;
SELECT * FROM STUDENTS;
ALTER TABLE STUDENTS ADD CONSTRAINT FULL_NM UNIQUE(FULL_NAME);
SELECT * FROM STUDENTS;
DROP TABLE STUDENTS;

SELECT * FROM SCHOOL;
SELECT * FROM ADDRESS;
SELECT * FROM STAFF;

-- INSERT

-- DML

INSERT INTO ADDRESS (ADDRESS_ID, STREET, CITY, STATE, COUNTRY) VALUES
('ADR1011', '44/5', 'DHANMONDI', 'DHAKA', 'BANGLADESH');

SELECT * FROM ADDRESS;

INSERT INTO ADDRESS VALUES
('ADR1003', '34/9', 'KALABAGAN', 'DHAKA', 'BANGLADESH');

SELECT * FROM ADDRESS;

INSERT INTO ADDRESS VALUES
('ADR1004', '65/9', 'MIRPUR', 'DHAKA', 'BANGLADESH'),
('ADR1005', 'RAMPURA', 'NAGPUR', 'DEHLI', 'INDIA'),
('ADR1006', 'CHAR MATHA', 'PIRGACHHA', 'RAGPUR', 'BANGLADESH');

SELECT * FROM ADDRESS;

-- UPDATE

UPDATE ADDRESS
SET ADDRESS_ID = 'ADR1002'
WHERE ADDRESS_ID = 'ADR1011';

SELECT * FROM ADDRESS;

UPDATE ADDRESS
SET COUNTRY = 'PAKISTAN', CITY = 'PANJAB'
WHERE ADDRESS_ID = 'ADR1004';

SELECT * FROM ADDRESS;


-- DELETE

DELETE FROM ADDRESS WHERE ADDRESS_ID = 'ADR1003';
SELECT * FROM ADDRESS;
DELETE FROM ADDRESS WHERE COUNTRY = 'BANGLADESH';
SELECT * FROM ADDRESS;
SELECT * FROM SCHOOL;
DELETE FROM SCHOOL;









































































































