-- FETCH ALL THE STUDENT DETAILS AND ADD REMARK TO THOSE STUDENTS WHO EARN MORE THAN THAN THE AVERAGE PAY
SELECT * FROM STUDENT;

SELECT *,CASE
	WHEN SALARY > (SELECT AVG(SALARY) FROM STUDENT) THEN 'OK'
	END AS REMARKS
FROM STUDENT;

SELECT S.*,CASE
	WHEN SALARY > AVERAGE_SALARY.AVG_SAL THEN 'GOOD'
	END AS REMARKS
FROM STUDENT AS S
CROSS JOIN (SELECT AVG(SALARY) AS AVG_SAL FROM STUDENT) AS AVERAGE_SALARY;

-- FIND THE STORE WHO SOLD MORE UNITS THAN AN AVERAGE THAN THE AVERAGE UNIT SOLD BY ALL STORES
SELECT * FROM SALES;

SELECT STORE_NAME, SUM(QUANTITY) AS TOTAL_SALES
FROM SALES
GROUP BY STORE_NAME
HAVING SUM(QUANTITY) > (SELECT AVG(QUANTITY) FROM SALES);

SELECT * FROM STUDENT;

CREATE TABLE STUDENT_HISTORY
(
	STD_ID INT
	, STD_NAME VARCHAR(50)
	, STD_DEPT VARCHAR(20)
	, SALARY INT
	, LOCATION VARCHAR(100)
);

SELECT * FROM STUDENT_HISTORY;


-- INSERT DATA INTO STUDENT HISTORY TABLE.MAKE SURE NOT INSERT DUPLICATE DATA INSERT
