-- FETCH THE ORDER SUMMARY (TO BE GIVEN TO CLINT/VENDOR)
-- ORDER ID, DATE, PRODUCT NAME, CUSTOMER NAME, COST
SELECT * FROM TB_ORDER_DETAILS;
SELECT * FROM TB_PRODUCT_INFO;
SELECT * FROM TB_CUSTOMER_DATA;

CREATE OR REPLACE VIEW ORDER_SUMMARY AS
SELECT O.ORD_ID, O.DATE AS ORDER_DATE, PROD_NAME, CUST_NAME, 
(P.PRICE*O.QUANTITY) - ((P.PRICE*O.QUANTITY) * DISC_PERCENT::FLOAT/100) AS COST
FROM TB_ORDER_DETAILS AS O
JOIN TB_PRODUCT_INFO AS P ON O.PROD_ID = P.PROD_ID
JOIN TB_CUSTOMER_DATA AS C ON C.CUST_ID = O.CUST_ID;

SELECT * FROM ORDER_SUMMARY;

-- RENAME THE COLUMN DATE TO ORDER DATE
ALTER VIEW ORDER_SUMMARY RENAME COLUMN DATE TO OREDER_DATE;

SELECT * FROM ORDER_SUMMARY;

-- RENAME THE VIEW ORDER SUMMARY TO ORDER SUMMARY VIEW 
ALTER VIEW ORDER_SUMMARY RENAME TO ORDER_SUMMARY_VIEW

SELECT * FROM ORDER_SUMMARY_VIEW;

-- DELETE THE ORDER SUMMARY VIEW

DROP VIEW ORDER_SUMMARY_VIEW;

-- CREATE A VIEW WITH EXPENSIVE PRODUCT WHICH PRICE IS MORE THAN 1000

CREATE OR REPLACE VIEW EXPENSIVE_PRODUCT AS
SELECT * FROM TB_PRODUCT_INFO WHERE PRICE > 1000;

SELECT * FROM EXPENSIVE_PRODUCT;

-- ADD A NEW COLUMN IN THE PRODUCT TABLE CALLED PRODUCT CONFIG
ALTER TABLE TB_PRODUCT_INFO ADD COLUMN PRODUCT_CONFIG VARCHAR(50);

SELECT * FROM TB_PRODUCT_INFO;

SELECT * FROM EXPENSIVE_PRODUCT;

-- ADD A NEW RECORD OF PRODUCT

INSERT INTO TB_PRODUCT_INFO VALUES
('P10', 'TEST', 'TEST', 1200, NULL);

UPDATE EXPENSIVE_PRODUCT
SET PROD_NAME = 'iPhone 13 Pro', BRAND = 'Apple'
WHERE PROD_ID = 'P10';

SELECT * FROM EXPENSIVE_PRODUCT;

SELECT * FROM TB_PRODUCT_INFO;

-- CREATE APPLE PRODUCT VIEW

CREATE VIEW APPLE_PRODUCTS
AS 
SELECT * FROM TB_PRODUCT_INFO WHERE BRAND = 'Apple';

SELECT * FROM APPLE_PRODUCTS;

-- INSERT A NRE RECORD IN THE APPLE PRODUCT VIEW (BUT INSERT OTHER PRODUCT)

INSERT INTO APPLE_PRODUCTS VALUES
('P20', 'NoteBook 20', 'Samsung', 2200, NULL);

SELECT * FROM APPLE_PRODUCTS;
SELECT * FROM TB_PRODUCT_INFO;

-- TRY TO WRITE A QUERY THAT OTHER PRODUCT NOT INSERT IN APPLE PRODUCT VIEW

CREATE OR REPLACE VIEW APPLE_PRODUCTS
AS 
SELECT * FROM TB_PRODUCT_INFO WHERE BRAND = 'Apple'
WITH CHECK OPTION;

INSERT INTO APPLE_PRODUCTS VALUES
('P20', 'NoteBook 20', 'Samsung', 2200, NULL);

