-- Find stores who's sales where better than the average sales accross all stores

-- Find total sales per each store
SELECT STORE_NAME, SUM(COST) AS TOTAL_COST_PER_STORE
FROM SALE
GROUP BY STORE_NAME;

-- Find average sales with respect to all stores
SELECT CAST(AVG(TOTAL_COST_PER_STORE) AS INT) AS AVERAGE_SALE_ALL_STORE
FROM (SELECT STORE_NAME, SUM(COST) AS TOTAL_COST_PER_STORE
		FROM SALE
		GROUP BY STORE_NAME) AS X;
		
-- Find stores who's sales where better than the average sales accross all stores
SELECT *
FROM (SELECT STORE_NAME, SUM(COST) AS TOTAL_COST_PER_STORE
		FROM SALE
		GROUP BY STORE_NAME) AS TOTAL_SALE
JOIN (SELECT CAST(AVG(TOTAL_COST_PER_STORE) AS INT) AS AVERAGE_SALE_ALL_STORE
		FROM (SELECT STORE_NAME, SUM(COST) AS TOTAL_COST_PER_STORE
				FROM SALE
				GROUP BY STORE_NAME) AS X) AS AVERAGE_SALE
				ON TOTAL_SALE.TOTAL_COST_PER_STORE > AVERAGE_SALE.AVERAGE_SALE_ALL_STORE;
				
-- Using WITH clause
WITH TOTAL_SALE(STORE_NAME, TOTAL_COST_PER_STORE) AS
	(SELECT STORE_NAME, SUM(COST) AS TOTAL_COST_PER_STORE
		FROM SALE
		GROUP BY STORE_NAME),
	AVERAGE_SALE(AVERAGE_SALE_ALL_STORE) AS
	(SELECT CAST(AVG(TOTAL_COST_PER_STORE) AS INT) AS AVERAGE_SALE_ALL_STORE
		FROM TOTAL_SALE)
SELECT *
FROM TOTAL_SALE AS  TS
JOIN AVERAGE_SALE AS AV ON TS.TOTAL_COST_PER_STORE > AV.AVERAGE_SALE_ALL_STORE;
