-- Scenario 1: Data duplicated based on SOME of the columns

-- CARS TABLE CREATE

create table if not exists cars
(
    id      int,
    model   varchar(50),
    brand   varchar(40),
    color   varchar(30),
    make    int
);

SELECT * FROM CARS;

insert into cars values (1, 'Model S', 'Tesla', 'Blue', 2018);
insert into cars values (2, 'EQS', 'Mercedes-Benz', 'Black', 2022);
insert into cars values (3, 'iX', 'BMW', 'Red', 2022);
insert into cars values (4, 'Ioniq 5', 'Hyundai', 'White', 2021);
insert into cars values (5, 'Model S', 'Tesla', 'Silver', 2018);
insert into cars values (6, 'Ioniq 5', 'Hyundai', 'Green', 2021);

SELECT * FROM CARS
ORDER BY MODEL, BRAND;

-- Requirement: Delete duplicate data from cars table. Duplicate record is identified based on the model and brand name.

-- SOLUTION 1: Delete using Unique identifier

SELECT MODEL, BRAND
FROM CARS
ORDER BY MODEL, BRAND;

-- FIND THE TOTAL SAME VALUE BASED ON MODEL, BRAND
-- LIST OUT ALL THE VALUE WHICH IS GREATE THAN 1
-- FIND OUT THE LATEST VALUE FROM THEM
-- DELETE THE LATEST VALUE FROM THE CARS TABLE

SELECT MODEL, BRAND, COUNT(*)
FROM CARS
GROUP BY MODEL, BRAND;

SELECT MODEL, BRAND, COUNT(*)
FROM CARS
GROUP BY MODEL, BRAND
HAVING COUNT(*) > 1;

SELECT MODEL, BRAND, COUNT(*), MAX(ID)
FROM CARS
GROUP BY MODEL, BRAND
HAVING COUNT(*) > 1;

SELECT * FROM CARS;

DELETE FROM CARS 
WHERE ID IN (SELECT MAX(ID)
			FROM CARS
			GROUP BY MODEL, BRAND
			HAVING COUNT(*) > 1);
			
SELECT * FROM CARS;

insert into cars values (5, 'Model S', 'Tesla', 'Silver', 2018);
insert into cars values (6, 'Ioniq 5', 'Hyundai', 'Green', 2021);

SELECT * FROM CARS;

-- SOLUTION 2: Using SELF join

-- FIND ALL THE LEATEST ID WHICH IS DUPLICATE

SELECT *
FROM CARS AS C1
JOIN CARS AS C2 ON C1.MODEL = C2.MODEL AND C1.BRAND = C2.BRAND;

SELECT c2.*
FROM CARS AS C1
JOIN CARS AS C2 ON C1.MODEL = C2.MODEL AND C1.BRAND = C2.BRAND
WHERE C1.ID < C2.ID;

DELETE FROM CARS
WHERE ID IN (SELECT C2.ID
			FROM CARS AS C1
			JOIN CARS AS C2 ON C1.MODEL = C2.MODEL AND C1.BRAND = C2.BRAND
			WHERE C1.ID < C2.ID)

SELECT * FROM CARS;


-- SOLUTION 3: Using Window functioN
-- ADD A ROW NUMBER COLUMN BASED ON MODEL, BRAND
-- FIND THE VALUE WHERE ROW NUMBER COLUMN IS GREATER THAN 1

SELECT * ,
ROW_NUMBER() OVER(PARTITION BY MODEL, BRAND) AS RN
FROM CARS;

SELECT *
FROM (SELECT * ,
		ROW_NUMBER() OVER(PARTITION BY MODEL, BRAND) AS RN
		FROM CARS) AS X
WHERE X.RN > 1;


DELETE FROM CARS
WHERE ID IN (SELECT ID
			FROM (SELECT *,
				 ROW_NUMBER() OVER(PARTITION BY MODEL, BRAND) AS RN
				 FROM CARS) AS X
			WHERE X.RN > 1)

SELECT * FROM CARS;

-- INSERT THESE TWO RECODR 

insert into cars values (5, 'Model S', 'Tesla', 'Silver', 2018);
insert into cars values (6, 'Ioniq 5', 'Hyundai', 'Green', 2021);

-- SOLUTION 4: Using MIN function. This delete even multiple duplicate records.
-- FIND THE MINIMUM ID BASED ON MODEL, AND BRAND
-- DELETE ALL THE VALUE FROM CARS EXCEPT MINIMUN ID VALUE

SELECT * FROM CARS;

SELECT MODEL, BRAND, MIN(ID)
FROM CARS
GROUP BY MODEL, BRAND;

DELETE FROM CARS
WHERE ID NOT IN (SELECT MIN(ID)
				FROM CARS
				GROUP BY MODEL, BRAND)

SELECT * FROM CARS;

-- CREATE CARS_BKP EMPTY TABEL STRUCTURE IS SAME
-- INSERT ALL THE UNIQUE VALUE IN THE CARS_BKP TALBE
-- DELETE THE CARS TABLE
-- RENAME THE CARS_BKP TABLE TO CARS TABLE

CREATE TABLE CARS_BKP
AS 
SELECT * FROM CARS WHERE 1 = 2;

SELECT * FROM CARS_BKP;

INSERT INTO CARS_BKP
SELECT *
FROM CARS
WHERE ID IN (SELECT MIN(ID)
			FROM CARS
			GROUP BY MODEL, BRAND);
			
SELECT * FROM CARS_BKP;

DROP TABLE CARS;

ALTER TABLE CARS_BKP RENAME TO CARS;

SELECT * FROM CARS;



-- SOLUTION 6: Using backup table without dropping the original table.

-- CREATE CARS_BKP EMPTY TABEL STRUCTURE IS SAME
-- INSERT ALL THE UNIQUE VALUE IN THE CARS_BKP TALBE
-- REMOVEL ALL ITEMS FROM THE CARS TABLE
-- INSERT ALL THE VALUES FROM CARS_BKP TABLE TO CARS TABLE
-- DELETE THE CARS_BKP TABLE

CREATE TABLE CARS_BKP
AS
SELECT * FROM CARS WHERE 1 = 2;

SELECT * FROM CARS_BKP;
SELECT * FROM CARS;

INSERT INTO CARS_BKP
SELECT *
FROM CARS
WHERE ID IN (SELECT MIN(ID)
			FROM CARS
			GROUP BY MODEL, BRAND);
		
SELECT * FROM CARS_BKP;

TRUNCATE TABLE CARS;

SELECT * FROM CARS;

INSERT INTO CARS
SELECT * FROM CARS_BKP;

DROP TABLE CARS_BKP;

