-- JOIN ==> INNER JOIN
-- LEFT JOIN ==> LEFT OUTER JOIN
-- LEFT JOIN ==> INNER JOIN + LEFT TABLE VALUE
-- RIGHT JOIN ==> RIGHT OUTER JOIN
-- RIGHT JOIN ==> INNER JOIN + RIGHT TABLE VALUE
-- FULL JOIN ==> FULL OUTER JOIN
-- FULL JOIN ==> INNER JOIN + RIGHT JOIN + LEFT JOIN

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
SELECT * FROM MANAGER;
SELECT * FROM PROJECTS;

-- INNER JOIN
-- FETCH THE EMPLOYEE NAME AND DEPARTMENT NAME THAT THEY BLONG TO
SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;

SELECT EMP.EMP_NAME, DPT.DEPT_NAME
FROM EMPLOYEE AS EMP
JOIN DEPARTMENT AS DPT ON EMP.DEPT_ID = DPT.DEPT_ID;

SELECT EMP.EMP_NAME, DPT.DEPT_NAME
FROM EMPLOYEE AS EMP
INNER JOIN DEPARTMENT AS DPT ON EMP.DEPT_ID = DPT.DEPT_ID
ORDER BY EMP_NAME;


-- LEFT JOIN
-- FETCH ALL THE EMPLOYEE NAME AND THEIR DEPARTMENT NAME THAT THEY ARE 
SELECT E.EMP_NAME, D.DEPT_NAME
FROM EMPLOYEE AS E
LEFT JOIN DEPARTMENT AS D ON E.DEPT_ID = D.DEPT_ID;



-- RIGHT JOIN

SELECT E.EMP_NAME, D.DEPT_NAME
FROM EMPLOYEE AS E
RIGHT JOIN DEPARTMENT AS D ON E.DEPT_ID = D.DEPT_ID;

-- FETCH DETAILS OF ALL EMP, THEIR MANAGER, THEIR DEPARTMENT, AND THE PROJECT THEY WORK ON
SELECT * FROM EMPLOYEE;
SELECT * FROM MANAGER;
SELECT * FROM DEPARTMENT;
SELECT * FROM PROJECTS;

SELECT E.EMP_NAME, D.DEPT_NAME, M.MANAGER_NAME, P.PROJECT_NAME
FROM EMPLOYEE AS E
LEFT JOIN DEPARTMENT AS D ON E.DEPT_ID = D.ID
INNER JOIN MANAGER AS M ON E.MANAGER_ID = M.MANAGER_ID
LEFT JOIN PROJECTS AS P ON P.TEAM_MEMBER_ID = E.EMP_ID;

-- FULL JOIN
-- FATCH ALL EMPLOYEE NAME AND DEPARTMENT NAME
SELECT E.EMP_NAME, D.DEPT_NAME
FROM EMPLOYEE AS E
FULL JOIN DEPARTMENT AS D ON E.DEPT_ID = D.DEPT_ID;

-- COMPANY TABLE CREATE

CREATE TABLE COMPANY
(
	COMPANY_ID VARCHAR(10)
	, COMPANY_NAME VARCHAR(50)
	, LOCATION VARCHAR(20)
);

SELECT * FROM COMPANY;

INSERT INTO COMPANY VALUES
('C001', 'TechTTSolution', 'Dhaka');

SELECT * FROM COMPANY;

-- CROSS JOIN

SELECT E.EMP_NAME, D.DEPT_NAME
FROM EMPLOYEE AS E
CROSS JOIN DEPARTMENT AS D;

-- WRITE A QUERY TO FATCH THE EMPLOYEE NAME AND CORESPONDING THEID DEPARTMENT NAME 
-- AND MAKE SURE TO DISPLAY THE COMPANY NAME AND LACATION CORRESPONDIG TO THE EMPLOYEE

SELECT E.EMP_NAME, D.DEPT_NAME, C.COMPANY_NAME, C.LOCATION
FROM EMPLOYEE AS E
INNER JOIN DEPARTMENT AS D ON E.DEPT_ID = D.DEPT_ID
CROSS JOIN COMPANY AS C;


-- NATURAL JOIN
SELECT E.EMP_NAME, D.DEPT_NAME
FROM EMPLOYEE AS E
NATURAL JOIN DEPARTMENT AS D;

SELECT * FROM DEPARTMENT;

ALTER TABLE DEPARTMENT RENAME COLUMN DEPT_ID TO ID;

SELECT * FROM DEPARTMENT;

SELECT E.EMP_NAME, D.DEPT_NAME
FROM EMPLOYEE AS E
NATURAL JOIN DEPARTMENT AS D;

-- FAMITY TABLE CREATE

CREATE TABLE FAMILY
(
	MEMBER_ID VARCHAR(10)
	, NAME VARCHAR(50)
	, AGE INT
	, PARENT_ID VARCHAR(10)
);

SELECT * FROM FAMILY;

INSERT INTO FAMILY VALUES
('F1', 'David', 4, 'F5'),
('F2', 'Carol', 10, 'F5'),
('F3', 'Michael', 12, 'F5');

SELECT * FROM FAMILY;

INSERT INTO FAMILY VALUES
('F4', 'Johnson', 36, ' ');

INSERT INTO FAMILY VALUES
('F5', 'Maryam', 40, 'F6'),
('F6', 'Stewart', 70, ' '),
('F7', 'Rohan', 8, 'F4'),
('F8', 'Asha', 6, 'F4');

SELECT * FROM FAMILY;

-- SELF JOIN
-- WRITE A QUERY TO FETCH THE CHILD NAME AND THEIR AGE CORESPONDING TO THEIR PARENT NAME AND THEIR AGE

SELECT CHILD.NAME AS CHILD_NAME
, CHILD.AGE AS CHILD_AGE
, PARENT.NAME AS PARENT_NAME
, PARENT.AGE AS PARENT_AGE
FROM FAMILY AS CHILD
JOIN FAMILY AS PARENT ON CHILD.PARENT_ID = PARENT.MEMBER_ID;


SELECT CHILD.NAME AS CHILD_NAME
, CHILD.AGE AS CHILD_AGE
, PARENT.NAME AS PARENT_NAME
, PARENT.AGE AS PARENT_AGE
FROM FAMILY AS CHILD
LEFT JOIN FAMILY AS PARENT ON CHILD.PARENT_ID = PARENT.MEMBER_ID;









































































































