-- CUSTOMER TABLE CREATE

CREATE TABLE CUSTOMERS
(
	CUSTOMER_ID INT
	, FIRST_NAME VARCHAR(50)
	, LAST_NAME VARCHAR(50)
	, AGE INT
	, EMAIL_ID VARCHAR(50)
);

SELECT * FROM CUSTOMERS;

INSERT INTO CUSTOMERS VALUES
(1, 'TOUHIDUZZAMAN', 'TUHIN', 27, 'TUHIN@XYZ.COM');

SELECT * FROM CUSTOMERS;

INSERT INTO CUSTOMERS VALUES
(3, 'ee', 'ff', 30, 'ef@xyz.com'),
(4, 'gg', 'hh', 36, 'gh@xyz.com');

SELECT * FROM CUSTOMERS;

COPY CUSTOMERS FROM 'J:\Code\SQL\Others\Data\\Copy.csv' DELIMITER ',' CSV HEADER;

SELECT * FROM CUSTOMERS;

COPY CUSTOMERS FROM 'J:\Code\SQL\Others\Data\\Copytext.txt' DELIMITER ',';

SELECT * FROM CUSTOMERS;

SELECT FIRST_NAME, LAST_NAME, AGE FROM CUSTOMERS;

SELECT FIRST_NAME, AGE FROM CUSTOMERS;

SELECT FIRST_NAME FROM CUSTOMERS;

SELECT DISTINCT FIRST_NAME FROM CUSTOMERS;


SELECT * FROM CUSTOMERS WHERE AGE = 25;

SELECT * FROM CUSTOMERS WHERE AGE > 30;

SELECT * FROM CUSTOMERS WHERE FIRST_NAME = 'Jay';

SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID = 4;

SELECT * FROM CUSTOMERS WHERE AGE > 20 AND AGE < 30;

SELECT * FROM CUSTOMERS WHERE AGE >= 20 AND AGE <= 30;

SELECT * FROM CUSTOMERS WHERE AGE < 20 OR AGE > 30;

SELECT * FROM CUSTOMERS WHERE NOT AGE = 25;

SELECT * FROM CUSTOMERS WHERE NOT AGE = 25 AND NOT FIRST_NAME = 'Jay';

SELECT * FROM CUSTOMERS;

UPDATE CUSTOMERS
SET CUSTOMER_ID = 2
WHERE CUSTOMER_ID = 3;

SELECT * FROM CUSTOMERS;

UPDATE CUSTOMERS
SET EMAIL_ID = 'tuhin@xyz.com'
WHERE CUSTOMER_ID = 1;

SELECT * FROM CUSTOMERS;

UPDATE CUSTOMERS
SET AGE = 39
WHERE AGE = 36;

SELECT * FROM CUSTOMERS;

UPDATE CUSTOMERS
SET FIRST_NAME = 'FF'
WHERE FIRST_NAME = 'ff';

SELECT * FROM CUSTOMERS;

DELETE FROM CUSTOMERS WHERE CUSTOMER_ID = 2;

SELECT * FROM CUSTOMERS;

DELETE FROM CUSTOMERS WHERE AGE = 25;

SELECT * FROM CUSTOMERS;

DELETE FROM CUSTOMERS WHERE LAST_NAME = 'TUHIN';

SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS ADD CITY VARCHAR(30);

SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS DROP CITY;

SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS ADD COUNTRY VARCHAR(20);

SELECT * FROM CUSTOMERS;

UPDATE CUSTOMERS
SET COUNTRY = 'BANGLADESH'
WHERE CUSTOMER_ID = 4;

SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS DROP COUNTRY;

SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS RENAME EMAIL_ID TO CUSTOMER_MAIL;

SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS RENAME COLUMN CUSTOMER_ID TO ID;

SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS ALTER COLUMN ID TYPE VARCHAR(20);

SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS ALTER COLUMN ID SET NOT NULL;

INSERT INTO CUSTOMERS (ID, FIRST_NAME, AGE) VALUES (12, 'MAHIM', 53);

SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS ALTER COLUMN ID DROP NOT NULL;

INSERT INTO CUSTOMERS (FIRST_NAME, AGE) VALUES ('KONA', 23);

SELECT * FROM CUSTOMERS;

DELETE FROM CUSTOMERS
WHERE FIRST_NAME = 'Jay';

SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS ADD PRIMARY KEY(FIRST_NAME);

INSERT INTO CUSTOMERS (FIRST_NAME, AGE) VALUES ('RANA', 44);

SELECT * FROM CUSTOMERS;

ALTER TABLE CUSTOMERS ADD CONSTRAINT AGE CHECK (AGE > 0);

INSERT INTO CUSTOMERS (FIRST_NAME, AGE) VALUES ('SHANTO', 9);

SELECT * FROM CUSTOMERS;


DROP TABLE CUSTOMERS;













